say: add speech model selection parameter
Add a `-m` parameter to the script that allows the user to specify a
different speech model to be used.

diff --git a/say b/say
--- a/say
+++ b/say
@@ -1,7 +1,34 @@
 #!/bin/bash
 
-# TODO receive as parameter
+# Default model
 MODEL=en_GB-alan-medium
+
+function usage() {
+    echo >&2 "Usage: $0 [-m MODEL] [text_to_read]"
+    echo >&2 "   -h      Display this help message"
+    echo >&2 "   -m MODEL The speech model to use (default: $MODEL)"
+    echo >&2 ""
+    echo >&2 "If no text is passed on the command line, it is read from stdin"
+}
+
+while getopts ":hm:" opt; do
+    case $opt in
+        h)
+            usage
+            exit 1
+            ;;
+        m)
+            MODEL="$OPTARG"
+            ;;
+        \?)
+            echo "Error: Invalid option: -$OPTARG" >&2
+            usage
+            exit 1
+            ;;
+    esac
+done
+
+shift $((OPTIND - 1))
 
 if [[ $MODEL =~ -medium$ ]]; then
     AUDIO_RATE=22050
